### PR TITLE
ScholarshipListcard tags bug

### LINKED ISSUE #748: Tags not rendering properly in List Card
**Describe the bug**
The tags are not rendering properly in the ScholarshipListCard component. 

**To Reproduce**

1. Go to https://dreamscholars.org/scholarships
2. You'll see weird circles on some scholarships

**Expected behavior**
I expect the tags to render properly, like in the detail card.

**Screenshots**

Screen Shot 2021-11-29 at 10 59 29 PM

**Desktop (please complete the following information):**

- OS: [e.g. iOS]: mac OS Monterey 12.0.1
- Browser [e.g. chrome, safari]: Firefox 
- Version [e.g. 22]: 94.0.2

**Additional context**

### PR DESCRIPTION
**Pull request by edwingl10**
## Motivation and Context

Fixes #748 
Also made changes to use `sx` props

## How Has This Been Tested?
locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] User visible change (users will notice UI or functional changes)

## Previewing Changes

1. Go to https://s4us-pr-749.onrender.com/scholarships.
2. Tags should now render properly

## Checklist:

- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: src/components/ScholarshipListCard.jsx [hunk 1]
```diff
@@ -62,35 +23,46 @@ function ScholarshipListCard({ scholarship }) {
...
             color="textSecondary"
-            className={classes.description}>
+            sx={{
+              display: '-webkit-box',
+              WebkitLineClamp: 5,
+              lineClamp: 5,
+              WebkitBoxOrient: 'vertical',
+              overflow: 'hidden',
+              whiteSpace: 'pre-line',
+              mb: 3,
```
Comment (josueetcom) [inline src/components/ScholarshipListCard.jsx:50]: Instead of this you can set the `paragraph` property to the element.

File: src/components/ScholarshipListCard.jsx [hunk 2]
```diff
@@ -62,35 +23,46 @@ function ScholarshipListCard({ scholarship }) {
           pathname: `/scholarships/${scholarship.id}`,
           state: { scholarship },
         }}>
-        <CardContent className={classes.content}>
-          <Typography variant="body1" className={classes.deadline}>
+        <CardContent sx={{ p: 3 }}>
+          <Typography variant="body1" sx={{ fontWeight: 'bold', mb: 1 }}>
```
Comment (josueetcom) [inline src/components/ScholarshipListCard.jsx:27]: Instead of `mb: 1` I think setting the `gutterBottom` property should work.

**Review by josueetcom — APPROVED** [review]
