### PR TITLE
experiment guards for GradeFilter and MajorFilter

### LINKED ISSUE #507: Hide currently broken functionality behind experiment guards
For preview launch, we don't want to have broken links/functionality across the site. Either remove the broken pieces or guard them using experiments (see #506 for an example).

I think the only functionality that's currently broken is the major filter

### PR DESCRIPTION
**Pull request by edwingl10**
## Motivation and Context

Added experiment guards to hide Grade filter and Major filter since they aren't fully functional yet.

Fixes #507 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] User visible change (users will notice UI or functional changes)

## Previewing Changes

1. Go to https://s4us-pr-569.onrender.com/scholarships.
2. notice how the Grade filter and the Major filter are hidden

## Checklist:

- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: src/components/FilterBar.jsx [hunk 1]
```diff
@@ -32,15 +33,18 @@ export default function FilterBar(props) {
   return (
     <Grid container spacing={2} className={classes.root}>
       <Grid item className={classes.alignText}>
-        <FilterDropDown label="Major" items={majors} />
-        <GradeLevelFilter />
+        {experiments.expshowMajorFilter && (
```
Comment (josueetcom) [inline src/components/FilterBar.jsx:36]:
```suggestion
        {experiments.expShowMajorFilter && (
```

Comment (josueetcom) [reply src/components/FilterBar.jsx:36]: You can see this doesn't work by going to https://s4us-pr-569.onrender.com/scholarships?expShowMajorFilter=1&expShowGradeFilter=1.

If you check the logs the experiment is enabled but this isn't showing up.

**Review by josueetcom — APPROVED** [review]
Fix the typo and it should be good.
