### PR TITLE
ScholarshipDetailCard bug fixes

### LINKED ISSUE #723: ScholarshipDetailCard doesn't show description newlines
**Describe the bug**
When I go to a scholarships like [this one](https://dreamscholars.org/scholarships/7IBHqGCVoQUxHpzmjuC0) there are no newlines. I guess we're not displaying them because in scholarships list page they are indeed shown.

**Expected behavior**

Preserved new lines

**Screenshots**

image

### PR DESCRIPTION
**Pull request by edwingl10**
## Motivation and Context

Fixes #723 and #584. 
Shows schools as part of the requirements section. 

## How Has This Been Tested?
Locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] User visible change (users will notice UI or functional changes)

## Previewing Changes

1. Go to https://s4us-pr-NUMBER.onrender.com/scholarships.
2. choose a scholarship
3. tags displayed properly, (if applicable)
4. schools requirement shown
5. newline in description shown properly

## Checklist:

- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: src/components/ScholarshipDetailCard.jsx [hunk 1]
```diff
@@ -227,13 +234,13 @@ export default function ScholarshipDetailCard({ scholarship, preview }) {
         <Grid container>
           {!tags
```
Comment (josueetcom) [inline src/components/ScholarshipDetailCard.jsx:235]: `tags` could be `[]`.
```suggestion
          {!tags || !tags.length
```

Alternatively we could render no tags in a different manner. Up to you

**Review by josueetcom — APPROVED** [review]

**Review by josueetcom — APPROVED** [review]
