### PR TITLE
fixed the glitch user home page flickers no scholarships when loading

### LINKED ISSUE #468: User home page flickers "no scholarships" when loading scholarships
**Describe the bug**

**To Reproduce**

(You need to have added a scholarship)

1. Go to https://dreamscholars.org/
2. Login.
3. Notice how for a split sec it shows the "no scholarships component".

**Expected behavior**

Loading icon?? Or blank?

**Screenshots**

**Desktop (please complete the following information):**

- OS: Chrome OS
- Browser [e.g. chrome, safari]: Chrome
- Version [e.g. 22]: 

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by gonzalo1330**
## Motivation and Context

It does not make sense as a user that has added a scholarship to have the "no scholarships component" appear as they should only see their list of scholarships added.
Users that have not added a scholarship will remain the same as they will be viewing the "no scholarships component".

Fixes #468 

## How Has This Been Tested?

Used the emulator to create a user that has a scholarship added and refreshed the page to ensure the "no scholarships component" does appear after loading scholarships. The list of added scholarships do appear and also removed the text that said "no more results".

Then I created another user in the emulator that does not have any scholarships added and the loading happens and after the "no scholarships component" does appear. 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] User visible change (users will notice UI or functional changes)

## Previewing Changes

1. Go to https://s4us-pr-486.onrender.com.
2. Login
3. There can be two scenarios: you haven't added scholarships the "no scholarships component" would appear, but if you have added a scholarship and you refresh the page you will notice that there is a loading that appears for a second then your added scholarships list will appear.

## Checklist:

- [ ] I have added tests to cover my changes.
* Pending test case to add

### CODE REVIEW

**Review by edwingl10 — APPROVED** [review]

File: src/pages/UserHome.jsx [hunk 1]
```diff
@@ -138,40 +138,42 @@ export default function UserHome() {
...
-        <>
-          <ScholarshipList scholarships={scholarships} />
-          {canLoadMore ? (
-            <Button
-              className={classes.loadMoreButton}
-              color="primary"
-              onClick={() => loadMoreScholarships(loadMoreFn)}>
-              Load More
-            </Button>
+        [
```
Comment (josueetcom) [inline src/pages/UserHome.jsx:144]: What is the array for? I think it works without it?

Comment (gonzalo1330) [reply src/pages/UserHome.jsx:144]: I don't think its an array, I think it was a way to do the nested conditional if/else thing I read it on stack overflow it gave warning

Comment (josueetcom) [reply src/pages/UserHome.jsx:144]: Ok I'm fine merging it as is

**Review by josueetcom — APPROVED** [review]
